### ISSUE TITLE
.env STRAPI_URL 

### ISSUE THREAD

**Issue by veronini** [veronini/dev4-make-it-personal#1]
Ik was dit nog vergeten te vragen tijdens het consult. 

In mijn index.js fetch ik ${process.env.STRAPI_URL}/tickets, en dat daar leest hij de STRAPI_URL perfect uit de .env.local

Wanneer ik de STRAPI_URL probeer op het halen in een ander page vindt hij de URL niet! (het gaat dan naar localhost:3000 waar mijn front-end aan het runnen is // localhost:3000/tickets....) 
Hierdoor zet ik de URL er hardcoded in maar dat is niet de bedoeling als ik dit ga deployen. 

Zet ik mijn env file verkeerd ? of moet ik het op een andere manier aanspreken?

**Comment by benoitboucart** [comment]
Kan het zijn dat het niet werkt waar je het client-side uitvoert (in de browser uitgevoerd). Aangezien je env variabele geen NEXT_PUBLIC_ prefix bevat zal deze client side niet gelezen kunnen worden. Publieke env variabele wilt zeggen dat die ook in de browser gelezen kan worden. Zonder die prefix zal je die enkel op de server (veiligere omgeving) kunnen lezen. Een publiekelijke env variabele mag dus nooit een wachtwoord bevatten maar wél een API URL.

Maw: je zal de variabele NEXT_PUBLIC_STRAPI_URL moeten noemen ipv STRAPI_URL (en je project opnieuw moeten opstarten). Zie ook de laatste labolessen.

Meer info vind je hier:
In order to expose a variable to the browser you have to prefix the variable with NEXT_PUBLIC_ For example:
https://nextjs.org/docs/basic-features/environment-variables

Succes!
